### ISSUE TITLE
summary_plotter error

### ISSUE THREAD

**Issue by alx552** [DanJeffries/RADweek#1]
Hello, 
I really liked you summary of STACKS.  
I am trying to use your script that generates summary plots for my own data but am running into an error (see below).  I was wondering if you know what could be going wrong?  I think this is python 2.7 but I also tried in 3 and got the same result. 
note: vcf was generated by STACKS v2.2

python summary_plotter.py /home/alx552/programs/summary-plotter/populations.snps.vcf 1111 False
  File "summary_plotter.py", line 108
    if not is.instance(switches, str):
            ^
SyntaxError: invalid syntax

**Comment by DanJeffries** [comment]
Hi, 

Glad its useful for you. The error is that `is.instance` should read `isinstance`. You can change this in your version yourself or re-download the script from here which is now updated. Note that this script was written using VCFs from an older version of stacks (1.48). It should still be ok, but if you have any more problems you can send me your vcf (or perhaps just the first 200 lines or something) and I'll update it. 

Best

Dan

**Comment by alx552** [comment]
Hi Dan, 

Thanks for the quick reply!  I made the edit you suggested and ran into a new error :
python summary_plotter.py /home/alx552/programs/summary-plotter/populations.snps.vcf 1111 False
Traceback (most recent call last):
  File "summary_plotter.py", line 342, in <module>
    Summary_plotter(vcf_file, switches, sort)
  File "summary_plotter.py", line 72, in Summary_plotter
    DP = sample_field.split(":")[1]
IndexError: list index out of range

I have attached my snps.vcf with just the first 200 lines. 
[test.vcf.zip](https://github.com/DanJeffries/RADweek/files/2967463/test.vcf.zip)
